builds:
    - binary: simplehttpserver
      main: cmd/simplehttpserver/simplehttpserver.go
      goos:
        - linux
        - windows
        - darwin
      goarch:
        - amd64
        - 386
        - arm
        - arm64
  
archives:
    - id: tgz
      format: tar.gz
      replacements:
          darwin: macOS
      format_overrides:
          - goos: windows
            format: zip

snapcrafts:
  - id: simplehttpserver
    replacements:
      darwin: macOS
    name: simplehttpserver
    publish: false
    summary: Go client to communicate with Chaos dataset API.
    description: |
      Go client to communicate with Chaos dataset API.
    grade: stable
    confinement: strict
    license: MIT
    base: core18
    apps:
      simplehttpserver:
        command: simplehttpserver
        plugs:
          - home
          - network
          - removable-media
          - dot-simplehttpserver
    plugs:
      dot-simplehttpserver:
        interface: personal-files
        write:
          - $HOME/.config/simplehttpserver