name: 🔨 Build Test

on:
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
  workflow_dispatch:


jobs:  
  build:
    name: Test Builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: projectdiscovery/actions/setup/go@v1

      - name: Test
        run: go test .
        working-directory: cmd/simplehttpserver/

      - name: Build
        run: go build .
        working-directory: cmd/simplehttpserver/