name: 🎉 Release Binary

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs: 
  release: 
    runs-on: ubuntu-latest
    steps: 
      - name: "Set up Go"
        uses: actions/setup-go@v4
        with: 
          go-version: 1.19
      - name: "Check out code"
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: "Create release on GitHub"
        uses: goreleaser/goreleaser-action@v4
        env: 
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          SLACK_WEBHOOK: "${{ secrets.RELEASE_SLACK_WEBHOOK }}"
          DISCORD_WEBHOOK_ID: "${{ secrets.DISCORD_WEBHOOK_ID }}"
          DISCORD_WEBHOOK_TOKEN: "${{ secrets.DISCORD_WEBHOOK_TOKEN }}"
        with: 
          args: "release --rm-dist"
          version: latest
          workdir: .