name: 🎉 Release Binary

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs: 
  release: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v7
      - uses: projectdiscovery/actions/setup/go@v1
      - name: "Create release on GitHub"
        uses: goreleaser/goreleaser-action@v7
        env: 
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          SLACK_WEBHOOK: "${{ secrets.RELEASE_SLACK_WEBHOOK }}"
          DISCORD_WEBHOOK_ID: "${{ secrets.DISCORD_WEBHOOK_ID }}"
          DISCORD_WEBHOOK_TOKEN: "${{ secrets.DISCORD_WEBHOOK_TOKEN }}"
        with: 
          args: "release --rm-dist"
          version: latest
          workdir: .